### ISSUE TITLE
Levae Room!!

### ISSUE THREAD

**Issue by localhoct** [seovchinnikov/clubhouse-web#7]
Error: WebSocket closed with reason: (1006).

![image](https://user-images.githubusercontent.com/72578456/113559119-11fa5f00-9616-11eb-8401-32c14556ce45.png)
can not join the room :)

**Comment by seovchinnikov** [comment]
Hey!
Have you run audio client first?

**Comment by localhoct** [comment]
No , How?

**Comment by localhoct** [comment]
i try to install

**Comment by seovchinnikov** [comment]
Please check readme 2.Install audio client

**Comment by localhoct** [comment]
`***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.

`
when i run `java -jar app.jar` got this i stop the Webapp by `docker stop clubhouse` and run the `java -jar app.jar` and run the docker again i got error 

`sudo docker start clubhouse
[sudo] password for talash: 
Error response from daemon: driver failed programming external connectivity on endpoint clubhouse (fb1c50417ab33466744d98845a42e9ccf5824414e4d80ee1af5c7de052ca1081): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use
Error: failed to start containers: clubhouse
`

**Comment by localhoct** [comment]
How change the docker port?
